version: '3.8'

services:
  web:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: ./server/compose/local/flask/Dockerfile
  
    image: web
    container_name: web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ./server:/app
    ports:
      - 5010:5000
    env_file:
      - ./server/.env/.dev-sample
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_CONFIG=development
      - DATABASE_URL=postgresql://flask_celery:flask_celery@db/flask_celery
      - SECRET_KEY=my_precious
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      # - db

  # db:
  #   image: postgres:13-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=flask_celery
  #     - POSTGRES_USER=flask_celery
  #     - POSTGRES_PASSWORD=flask_celery

  redis:
    image: redis:6-alpine

  celery_worker:
    # platform: linux/amd64
    build:
      context: .
      dockerfile: ./server/compose/local/flask/Dockerfile
    image: worker
    command: /start-celeryworker
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env/.dev-sample
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_CONFIG=development
      - DATABASE_URL=postgresql://flask_celery:flask_celery@db/flask_celery
      - SECRET_KEY=my_precious
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      # - db

volumes:
  postgres_data: