SecurityGroupIds:
- sg-00c487a2d59a5fa6e
ec2_image_id: ami-0568773882d492fc8
ec2_instance_id: i-040df21cb37da2346
ec2_instance_type: t2.large
ec2_volume: '20'
key_pair_name: JL-2
login_user: ec2-user
tags:
- Key: managedBy
  Value: boto3
- Key: Name
  Value: gcd-ec2-bastion
- Key: project
  Value: pvinsight
vpc_id: vpc-a27c77ca
