# AWS parameters used for cli.
aws_config:
  cluster_name: "gcd-eks"                 # The cluster name has to be matched to `eks/cluster.yaml`
  nodegroup_name: "gcd-nodegroup"         # The nodegroup name has to be matched to `eks/cluster.yaml`
  eks_nodes_number: 5                     # Total ec2 instances
  scale_eks_nodes_wait_time : 90          # in second
  interval_of_check_sqs_in_second: 3      # in second
  interval_of_total_wait_time_of_sqs: 300 # in second.
  interval_of_wait_pod_ready: 90          # in second


# Parameters used for cli in k8s config.
services_config_list:
  worker:
      desired_replicas: 10 # Define how many workers run parallel in k8s. The generated workers spread evenly among eks nodes.
      imagePullPolicy: "Always"
      deployment_file: "./config/k8s/worker.deployment.yaml"
      service_file: ""
      image_name: "worker"
      image_tag: "latest"
  server:
      desired_replicas: 1
      imagePullPolicy: "Always"
      deployment_file: "./config/k8s/server.deployment.yaml"
      service_file: "./config/k8s/server.services.yaml"
      image_name: "server"
      image_tag: "latest"
  redis:
      desired_replicas: 1
      imagePullPolicy: "Always"
      deployment_file: "./config/k8s/redis.deployment.yaml"
      service_file: "./config/k8s/redis.services.yaml"
      image_name: "redis"
      image_tag: "latest"

  rabbitmq:
      desired_replicas: 1
      imagePullPolicy: "Always"
      deployment_file: "./config/k8s/rabbitmq.deployment.yaml"
      service_file: "./config/k8s/rabbitmq.services.yaml"
      image_name: "rabbitmq"
      image_tag: "latest"

# Parameters pass to woker container.
worker_config:
  solver:
    solver_name: "MOSEK"
    saved_solver_bucket: "pv.insight.test"
    solver_lic_local_path: "./config/license"
    solver_lic_target_path: "/root/mosek"     # This location inside worker container is requires by MOSEK
    saved_temp_path_in_bucket: "lic_temp"     # Temporaty file location on S3 lic_temp/<user_id>.it grenerated in run-time and deleted after program completed.
    solver_lic_file_name: "mosek.lic"
  data_bucket: "pv.insight.nrel"                      # Bucket contains origin data files.
  default_process_files: ["PVO/PVOutput/40588.csv"]   # Default process files. If users do not use option -n command.
  process_column_keywords: ["Power(W)"]         # partial match. Process all matched column name "WS_5"WS_5_DateUTC
  saved_bucket: "pv.insight.test"                     # Bucket of saved files.
  saved_path: "results"                               # Path of saved files in bucket
  dynamodb_tablename: "gcd_logs_dynamodb" # pre-define in AWS us-east-2
  interval_of_check_task_status: "5"    # in second
  interval_of_exit_check_status: "900"  # in second. If a task status does not update in thia period. stop check individual status and revoke this task.
  acccepted_idle_time: "240"
  saved_rumtime_image_name: None          # "runtime-{user_id}.png"
  saved_performance_file: None            # "performance-{user_id}.txt"
  saved_data_target_filename: None        # "results-{user_id}.csv"
  saved_logs_target_filename: None        # "logs-{user_id}.csv"
  saved_error_target_filename: None        # "error-{user_id}.csv"
  curr_process_file : None      # It's a hint column that is generated in the CLI run-time.
  curr_process_column : None    # It's a hint column that is generated in the CLI run-time.
  aws_access_key : None         # It's a hint column that is generated in the CLI run-time.
  aws_secret_access_key : None  # It's a hint column that is generated in the CLI run-time.
  aws_region : None             # It's a hint column that is generated in the CLI run-time.
  sns_topic : None              # It's a hint column that is generated in the CLI run-time.
  user_id : None           # It's a hint column that is generated in the CLI run-ime.
