# process file 
general:
  environment: "local"  # "local" , "AWS"
  container_type: "docker"  # "docker" , "kubernetes"
  container_name: "web"     # "web" . "webapp"
  interval_of_check_task_status: "1" # in second
  interval_of_exit_check_status: "60" # in second. If the task status didn't update after this period. stop check status 

files_config:
  bucket: "pv.insight.nrel"
  process_all_files : "False" # If true, this program will run all files in this bucket. The files parameters will be ignored.
  # files: ["PVO/PVOutput/10059.csv","PVO/PVOutput/10010.csv","PVO/PVOutput/10664.csv"]
  # files: ["PVO/PVOutput/10059.csv","PVO/PVOutput/10010.csv"]
  files: ["PVO/PVOutput/10059.csv"]
  column_names: ["Power(W)"]
  # column_names: ["Power(W)","W"]
  # column_names: ["W"]
output:
  saved_bucket: "pv.insight.test"
  saved_tmp_path: "tmp"
  saved__target_path: "results"
  saved__target_filename: "04262022_results.csv"
  dynamodb_tablename: "GCD-LOGS_TABLE" # pre-define in AWS us-east-2
  saved_logs_target_path: "results"
  saved_logs_target_filename: "logs.csv"


solardata:
  power_col: "None"
  min_val: -5
  max_val: "None"
  zero_night: True
  interp_day: True
  fix_shifts: True
  density_lower_threshold: 0.6
  density_upper_threshold: 1.05
  linearity_threshold: 0.1
  clear_day_smoothness_param: 0.9
  clear_day_energy_param: 0.8
  verbose: False
  start_day_ix: "None"
  end_day_ix: "None"
  c1: "None"
  c2: 500.0
  solar_noon_estimator: "com"
  correct_tz: True
  extra_cols: "None"
  daytime_threshold: "0.1"
  units: "W"
  # solver: "None"
  solver: "MOSEK"
