# AWS parameters used for cli.
aws_config:
  cluster_name: "gcd-eks"
  nodegroup_name: "gcd-nodegroup"
  eks_nodes_number: 5 # total ec2 instances
  scale_eks_nodes_wait_time : 90 # in second
  interval_of_check_sqs_in_second: 3 # in second
  interval_of_total_wait_time_of_sqs: 300 # in second.
  interval_of_wait_pod_ready: 90 # in second


# Parameters used for cli in k8s config.
services_config_list:
  worker:
      desired_replicas: 5 # Define how many workers run parallel in k8s
      imagePullPolicy: "Always"
      deployment_file: "./config/k8s/worker.deployment.yaml"
      service_file: ""
      image_name: "worker"
      image_tag: "latest"
  server:
      desired_replicas: 1
      imagePullPolicy: "Always"
      deployment_file: "./config/k8s/server.deployment.yaml"
      service_file: "./config/k8s/server.services.yaml"
      image_name: "server"
      image_tag: "latest"
  redis:
      desired_replicas: 2
      imagePullPolicy: "Always"
      deployment_file: "./config/k8s/redis.deployment.yaml"
      service_file: "./config/k8s/redis.services.yaml"
      image_name: "redis"
      image_tag: "latest"

  rabbitmq:
      desired_replicas: 2
      imagePullPolicy: "Always"
      deployment_file: "./config/k8s/rabbitmq.deployment.yaml"
      service_file: "./config/k8s/rabbitmq.services.yaml"
      image_name: "rabbitmq"
      image_tag: "latest"

# Parameters pass to woker container.
worker_config:
  solver:
    solver_name: "MOSEK"
    saved_solver_bucket: "pv.insight.test"
    solver_lic_local_path: "./config/license"
    solver_lic_target_path: "/root/mosek"
    saved_temp_path_in_bucket: "lic_temp" # grenerated in run-time.
    solver_lic_file_name: "mosek.lic"
  data_bucket: "pv.insight.nrel"
  default_process_files: ["PVO/PVOutput/40588.csv"]
  process_column_keywords: ["Power(W)","(W)"] # partial match
  saved_bucket: "pv.insight.test"
  saved_path: "results"
  dynamodb_tablename: "gcd_logs_dynamodb" # pre-define in AWS us-east-2
  interval_of_check_task_status: "5"    # in second
  interval_of_exit_check_status: "900"  # in second. If a task status does not update in thia period. stop check individual status and revoke this task.
  saved_rumtime_image_name: None          # runtime-{user_id}.png"
  saved_performance_file: None            #"performance-{user_id}.txt"
  saved_data_target_filename: None        #"results-{user_id}.csv"
  saved_logs_target_filename: None        #"logs-{user_id}.csv"
  curr_process_file : None      # It's a hint column that is generated in the CLI run-time.
  curr_process_column : None    # It's a hint column that is generated in the CLI run-time.
  aws_access_key : None         # It's a hint column that is generated in the CLI run-time.
  aws_secret_access_key : None  # It's a hint column that is generated in the CLI run-time.
  aws_region : None             # It's a hint column that is generated in the CLI run-time.
  sns_topic : None              # It's a hint column that is generated in the CLI run-time.
  user_id : None           # It's a hint column that is generated in the CLI run-ime.
