apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: flower
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: flower
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: flower
      containers:
        - name: flower
          image: flower:latest
          imagePullPolicy: IfNotPresent
          command: ["/start-flower"]
          env:
            - name: FLASK_APP
              value: app
            - name: FLASK_ENV
              value: development
            - name: FLASK_CONFIG
              value: "development"
            - name: CELERY_BROKER_URL
              value: "amqp://admin:admin@rabbitmq:5672/"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"