apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: server
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server:latest
        command: ["/start"]
        imagePullPolicy: IfNotPresent
        env:
          - name: FLASK_APP
            value: app
          - name: FLASK_ENV
            value: development
          - name: FLASK_CONFIG
            value: "development"
          - name: CELERY_BROKER_URL
            value: "amqp://admin:admin@rabbitmq:5672/"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis:6379/0"
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "250m"
        #   limits:
        #     memory: "2Gi"
        #     cpu: "500m"
