apiVersion: apps/v1
# kind: Deployment
kind: DaemonSet
metadata:
  name: worker
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: worker
    spec:
      # topologySpreadConstraints:
      #   - maxSkew: 1
      #     topologyKey: kubernetes.io/hostname
      #     whenUnsatisfiable: DoNotSchedule
      #     labelSelector:
      #       matchLabels:
      #         app: worker
      containers:
        - name: worker
          image: worker:latest
          imagePullPolicy: IfNotPresent
          command: ["/start-celeryworker"]
          env:
            - name: FLASK_APP
              value: app
            - name: FLASK_ENV
              value: development
            - name: FLASK_CONFIG
              value: "development"
            - name: CELERY_BROKER_URL
              value: "amqp://admin:admin@rabbitmq:5672/"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis:6379/0"
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 1000m



# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: worker
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: worker
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 500
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       averageUtilization: 50
