apiVersion: v1
kind: Service
metadata:
  name: server

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: server


  ports:
    - name: http
      port: 5000
      targetPort: 5000

  type: ClusterIP
