name: Docker Compose Actions Workflow
on: 
  workflow_dispatch: # Allow for running this manually.
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: ./gismoclouddeploy/docker-compose build