folder_config:
  bucket: "pv.insight.nrel"
  folders: ["PVO/PVOutput"]
  column_names: ["Power(W)","W"]
  save_bucket: "pv.insight.test"
  save_path: "tmp"
  save_filename: "result.csv"

output:
  save_bucket: "pv.insight.test"
  save_path: "tmp"
  save_filename: "result.csv"

