apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: worker:latest
        imagePullPolicy: Always
        command: ["/start-celeryworker"]
        env:
          - name: FLASK_APP
            value: app
          - name: FLASK_ENV
            value: development
          - name: FLASK_CONFIG
            value: "development"
          - name: CELERY_BROKER_URL
            value: "amqp://admin:admin@rabbitmq:5672/"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis:6379/0"
