apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: database
  name: postgres
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: postgres
    spec:
      containers:
      - name: postgres
        image: jimmyleu76/postgres-13:latest
        env:
          - name: POSTGRES_USER
            value: sample
            # valueFrom:
            #   secretKeyRef:
            #     name: postgres-credentials
            #     key: user
          - name: POSTGRES_PASSWORD
            value: pleasechangeme
            # valueFrom:
            #   secretKeyRef:
            #     name: postgres-credentials
            #     key: password
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres-volume-mount
        persistentVolumeClaim:
          claimName: postgres-pvc
