apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: 041414866712.dkr.ecr.us-east-2.amazonaws.com/worker:latest
        imagePullPolicy: Always
        command: ["/start-celeryworker"]
        env:
          - name: FLASK_APP
            value: app 
          - name: FLASK_ENV
            value: development 
          - name: FLASK_CONFIG
            value: "development"
          - name: CELERY_BROKER_URL
            value: "amqp://admin:admin@rabbitmq-service:5672/"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis:6379/0"
          - name: SNS_TOPIC
            value: arn:aws:sns:us-east-2:041414866712:gismo-cloud-deploy-sns
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-credentials
                key: aws-secret-access-key
          - name: AWS_DEFAULT_REGION
            value: us-east-2
