apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: web:latest
        command: ["/start"]
        imagePullPolicy: IfNotPresent
        env:
          - name: FLASK_APP
            value: app 
          - name: FLASK_ENV
            value: development 
          - name: FLASK_CONFIG
            value: "development"
          - name: CELERY_BROKER_URL
            value: "amqp://admin:admin@rabbitmq-service:5672/"
          - name: CELERY_RESULT_BACKEND
            value: "redis://redis:6379/0"



