apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 041414866712.dkr.ecr.us-east-2.amazonaws.com/server:latest
        command: ["/start"]
        imagePullPolicy: Always
        env:
          - name: FLASK_APP
            value: app 
          - name: FLASK_ENV
            value: development 
          - name: FLASK_CONFIG
            value: "development"
          - name: CELERY_BROKER_URL
            value: "amqp://admin:admin@rabbitmq-service:5672/"
          - name: CELERY_RESULT_BACKEND
            value: "redis://back-api:6379/0"
          - name: DATABASE_URL
            value: "postgresql://sample:pleasechangeme@postgres-services/flask_celery"
          - name: SECRET_KEY  
            value: my_precious
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-access-key-id
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret-access-key
                key: aws-secret-access-key
          - name: AWS_DEFAULT_REGION
            value: us-east-2

