SecurityGroupIds:
- sg-00c487a2d59a5fa6e
ec2_image_id: ami-0568773882d492fc8
ec2_instance_id: i-010523f886e1b2d45
ec2_instance_type: t2.large
ec2_volume: '16'
key_pair_name: JL-2
tags:
- Key: managedBy
  Value: boto3
- Key: Name
  Value: gcd-dele
- Key: project
  Value: pvinsight
vpc_id: vpc-a27c77ca
