SecurityGroupIds:
- sg-00c487a2d59a5fa6e
ec2_image_id: ami-0568773882d492fc8
ec2_instance_id: i-0abb4644f5925b1e3
ec2_instance_type: t2.large
ec2_volume: 16
key_pair_name: gcd_eks_JL
pem_location: /Users/jimmyleu/Development/AWS
public_ip: 18.189.14.102
tags:
- Key: Name
  Value: gcd_eks_bastion
- Key: project
  Value: pvinsight
- Key: manageBy
  Value: boto3
user_name: ec2-user
vpc_id: vpc-a27c77ca
