apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: gcd-eks-cluster
  region: us-east-2
managedNodeGroups:
- name: gcd-node-group-lt
  # launchTemplate:
  #   id: lt-id
  #   version: "1"