"""Initial migration.

Revision ID: 9209ce292141
Revises: 
Create Date: 2022-03-21 09:43:50.577464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9209ce292141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solardata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=128), nullable=False),
    sa.Column('bucket_name', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=128), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('column_name', sa.String(length=128), nullable=False),
    sa.Column('process_time', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('capacity_estimate', sa.Float(), nullable=False),
    sa.Column('data_sampling', sa.Float(), nullable=False),
    sa.Column('capacity_changes', sa.Float(), nullable=False),
    sa.Column('num_clip_points', sa.Float(), nullable=False),
    sa.Column('normal_quality_scores', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(length=256), nullable=True),
    sa.Column('power_units', sa.String(length=128), nullable=False),
    sa.Column('time_shifts', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('solardata')
    # ### end Alembic commands ###
