import enum


class SNSSubjectsAlert(enum.Enum):
    PROCESS_FILE_ERROR = "PROCESS_FILE_ERROR"
    All_TASKS_COMPLETED = "All_TASKS_COMPLETED"

    TASK_START = "TASK_START"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    TIMEOUT = "TIMEOUT"
    SAVED_DATA = "SAVED_DATA"
