import enum


class SNSSubjectsAlert(enum.Enum):
    PROCESS_FILE_ERROR = "PROCESS_FILE_ERROR"
    All_TASKS_COMPLETED = "All_TASKS_COMPLETED"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    TIMEOUT = "TIMEOUT"
