ec2_image_id: ami-0568773882d492fc8
ec2_instance_id: 
securitygroup_name: 'SSH-ONLY'
ec2_instance_type: t2.large
ec2_volume: '20'
key_pair_name:
login_user: ec2-user
tags:
- Key: managedBy
  Value: boto3
