SecurityGroupIds:
ec2_image_id: ami-0568773882d492fc8
ec2_instance_id: 
ec2_instance_type: t2.large
ec2_volume: '20'
key_pair_name:
vpc_id: 
login_user: ec2-user
tags:
- Key: managedBy
  Value: boto3
