apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: solar-2  # eks cluster name
  region: us-east-2 # region 
  tags:
    project: pvinsight 
    manage: eksctl


nodeGroups:
  - name: solar-2 # nodegroup name
    instanceType: t2.large
    desiredCapacity: 0
    minSize: 0
    maxSize: 64
    tags:
      project: pvinsight
      manage: eksctl
