apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: solarDeleteme
  region: us-east-2
  tags:
    project: pvinsight
    manage: eksctl
# vpc:
#   id: "vpc-11111"
#   subnets:
#     private:
#       us-east-2a: { id: subnet-01234567890abcdef }

nodeGroups:
  - name: solarDeleteme
    instanceType: t2.large
    desiredCapacity: 0
    minSize: 0
    maxSize: 64
    tags:
      project: pvinsight
      manage: eksctl
