apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testSolar
  region: us-east-2
  tags:
    project: pvinsight
    manage: eksctl

nodeGroups:
  - name: testSolar
    instanceType: t2.large
    desiredCapacity: 0
    minSize: 0
    maxSize: 64
    tags:
      project: pvinsight
      manage: eksctl
