apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcd-eks-cluster
  region: us-east-2
  tags:
    project: pvinsight
    manage: eksctl


nodeGroups:
  - name: gcd-nodegroup
    instanceType: t2.xlarge
    desiredCapacity: 1
    tags:
      project: pvinsight
      manage: eksctl