apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gcd-eks-cluster
  region: us-east-2
  tags:
    project: pvinsight
    manage: eksctl


nodeGroups:
  - name: gcd-nodegroup
    instanceType: t2.xlarge
    desiredCapacity: 2
    volumeSize: 80
    privateNetworking: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
    tags:
      project: pvinsight
      manage: eksctl