apiVersion: v1
kind: Service
metadata:
  name: flask-services

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp


  ports:
    - name: http
      port: 5000
      nodePort: 30080

  type: NodePort
