apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: gcd-jimmysmacbookpro2local-1663358624
  region: us-east-2
  tags:
    manage: eksctl
    project: pvinsight
nodeGroups:
- desiredCapacity: 0
  instanceType: t2.large
  maxSize: 64
  minSize: 0
  name: gcd-jimmysmacbookpro2local-1663358624
  tags:
    manage: eksctl
    project: pvinsight
